name: JS CI

on:
  pull_request:
    branches:
      - master
      - 'release/**'
    paths:
      - src/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: NPM Cache
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: NPM install
        run: npm install

      - name: Lint JS
        run: npm run lint:js

      - name: Unit tests
        run: npm run test:unit
