name: GenerateBlocks JS CI

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: NPM install
        run: npm install

      - name: Lint JS
        run: npm run lint:js

      - name: Unit tests
        run: npm run test:unit
